src/Web/Jokify.Web/Controllers/JokesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Jokify.Services.DataServices;
using Jokify.Services.MachineLearning;
using Jokify.Services.Models.Jokes;
using Jokify.Web.Model.Jokes;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;

namespace Jokify.Web.Controllers
{
    public class JokesController : BaseController
    {
        private readonly IJokesService jokesService;
        private readonly ICategoriesService categoriesService;
        private readonly IJokesCategorizer jokesCategorizer;

        public JokesController(
            IJokesService jokesService,
            ICategoriesService categoriesService,
            IJokesCategorizer jokesCategorizer)
        {
            this.jokesService = jokesService;
            this.categoriesService = categoriesService;
            this.jokesCategorizer = jokesCategorizer;
        }

        [Authorize]
        public IActionResult Create()
        {
            this.ViewData["Categories"] = this.categoriesService.GetAll()
                .Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.NameAndCount,
                });
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateJokeInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var id = await this.jokesService.Create(input.CategoryId, input.Content);
            return this.RedirectToAction("Details", new { id = id });
        }

        public IActionResult Details(int id)
        {
            var joke = this.jokesService.GetJokeById<JokeDetailsViewModel>(id);
            return this.View(joke);
        }

        [HttpPost]
        public SuggestCategoryResult SuggestCategory(string joke)
        {
            var category = this.jokesCategorizer.Categorize("MlModels/JokesCategoryModel.zip", joke);
            var categoryId = this.categoriesService.GetCategoryId(category);
            return new SuggestCategoryResult { CategoryId = categoryId ?? 0, CategoryName = category };
        }

        [HttpPost]
        public object RateJoke(int jokeId, int rating)
        {
            var rateJoke = this.jokesService.AddRatingToJoke(jokeId, rating);
            if (!rateJoke)
            {
                return Json($"An error occurred while processing your vote");
            }
            var successMessage = $"You successfully rated the joke with rating of {rating}";
            return Json(successMessage);
        }
    }

    public class SuggestCategoryResult
    {
        public int CategoryId { get; set; }

        public string CategoryName { get; set; }
    }
}

src/Web/Jokify.Web/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Jokify</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Jokify</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Categories" asp-action="Index">Categories</a></li>
                    @if (this.User.Identity.IsAuthenticated)
                    {
                        <li><a asp-controller="Categories" asp-action="Create" asp-area="Administration">Administration</a></li>
                        <li><a asp-area="" asp-controller="Jokes" asp-action="Create">Create</a></li>
                    }
                    <li><a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="main">
        <div class="container body-content">
            @RenderBody()
        </div>
    </div>

    <footer class="footer">
        <div class="container">
            <p>&copy; 2019 - Jokify</p>
        </div>
    </footer>

    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.form-password svg').click(function () {
                if ($(this).parents('.form-password').hasClass('active')) {
                    $(this).siblings('input').attr('type', 'password');
                    $(this).parents('.form-password').removeClass('active');
                } else {
                    $(this).siblings('input').attr('type', 'text');
                    $(this).parents('.form-password').addClass('active');
                }
            });
        });
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>